apiVersion: apps/v1
kind: Deployment
metadata:
  name: yugiapi-express-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yugiapi-express
  template:
    metadata:
      labels:
        app: yugiapi-express
    spec:
      containers:
      - name: yugiapi
        image: jujocave/yugiapi
        ports:
        - containerPort: 3000
        env:
          - name: MONGO_URI
            value: "mongodb://mongodb:27017/yugibase" # Usar la dirección de MongoDB en Kubernetes
          - name: PORT
            value: "4000"
