apiVersion: apps/v1
kind: Deployment
metadata:
  name: yugiapi-express-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yugiapi-express
  template:
    metadata:
      labels:
        app: yugiapi-express
    spec:
      containers:
      - name: yugiapi
        image: jujocave/yugiapi-express:v1
        ports:
        - containerPort: 3000
