apiVersion: v1
kind: Service
metadata:
  name: yugiapi-express-service
spec:
  selector:
    app: yugiapi-express
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
